---
resources:
- name: animated-computing-machine
  type: git
  source:
    uri: https://github.com/zaksoup/animated-computing-machine.git
    branch: master

- name: in1x
  type: s3
  source:
    bucket: animated-computing-machine
    versioned_file: in1x/bit
    access_key_id: {{access-key-id}}
    secret_access_key: {{secret-access-key}}
    region_name: us-west-2

- name: in2x
  type: s3
  source:
    bucket: animated-computing-machine
    versioned_file: in2x/bit
    access_key_id: {{access-key-id}}
    secret_access_key: {{secret-access-key}}
    region_name: us-west-2

- name: in3x
  type: s3
  source:
    bucket: animated-computing-machine
    versioned_file: in3x/bit
    access_key_id: {{access-key-id}}
    secret_access_key: {{secret-access-key}}
    region_name: us-west-2

- name: in4x
  type: s3
  source:
    bucket: animated-computing-machine
    versioned_file: in4x/bit
    access_key_id: {{access-key-id}}
    secret_access_key: {{secret-access-key}}
    region_name: us-west-2

- name: in1y
  type: s3
  source:
    bucket: animated-computing-machine
    versioned_file: in1y/bit
    access_key_id: {{access-key-id}}
    secret_access_key: {{secret-access-key}}
    region_name: us-west-2

- name: in2y
  type: s3
  source:
    bucket: animated-computing-machine
    versioned_file: in2y/bit
    access_key_id: {{access-key-id}}
    secret_access_key: {{secret-access-key}}
    region_name: us-west-2

- name: in3y
  type: s3
  source:
    bucket: animated-computing-machine
    versioned_file: in3y/bit
    access_key_id: {{access-key-id}}
    secret_access_key: {{secret-access-key}}
    region_name: us-west-2

- name: in4y
  type: s3
  source:
    bucket: animated-computing-machine
    versioned_file: in4y/bit
    access_key_id: {{access-key-id}}
    secret_access_key: {{secret-access-key}}
    region_name: us-west-2

- name: out1
  type: s3
  source:
    bucket: animated-computing-machine
    versioned_file: out1/bit
    access_key_id: {{access-key-id}}
    secret_access_key: {{secret-access-key}}
    region_name: us-west-2

- name: out2
  type: s3
  source:
    bucket: animated-computing-machine
    versioned_file: out2/bit
    access_key_id: {{access-key-id}}
    secret_access_key: {{secret-access-key}}
    region_name: us-west-2

- name: out3
  type: s3
  source:
    bucket: animated-computing-machine
    versioned_file: out3/bit
    access_key_id: {{access-key-id}}
    secret_access_key: {{secret-access-key}}
    region_name: us-west-2

- name: out4
  type: s3
  source:
    bucket: animated-computing-machine
    versioned_file: out4/bit
    access_key_id: {{access-key-id}}
    secret_access_key: {{secret-access-key}}
    region_name: us-west-2

- name: c1
  type: s3
  source:
    bucket: animated-computing-machine
    versioned_file: c1/bit
    access_key_id: {{access-key-id}}
    secret_access_key: {{secret-access-key}}
    region_name: us-west-2

- name: c2
  type: s3
  source:
    bucket: animated-computing-machine
    versioned_file: c2/bit
    access_key_id: {{access-key-id}}
    secret_access_key: {{secret-access-key}}
    region_name: us-west-2

- name: c3
  type: s3
  source:
    bucket: animated-computing-machine
    versioned_file: c3/bit
    access_key_id: {{access-key-id}}
    secret_access_key: {{secret-access-key}}
    region_name: us-west-2

- name: c4
  type: s3
  source:
    bucket: animated-computing-machine
    versioned_file: c4/bit
    access_key_id: {{access-key-id}}
    secret_access_key: {{secret-access-key}}
    region_name: us-west-2

jobs:
- name: setx
  plan:
  - get: animated-computing-machine
  - task: set
    file: animated-computing-machine/set.yml
    params:
      out1: 1
      out2: 0
      out3: 0
      out4: 0
  - aggregate:
    - put: in1
      resource: in1x
      params:
        file: out1/bit
    - put: in2
      resource: in2x
      params:
        file: out2/bit
    - put: in3
      resource: in3x
      params:
        file: out3/bit
    - put: in4
      resource: in4x
      params:
        file: out4/bit

- name: sety
  plan:
  - get: animated-computing-machine
  - task: set
    file: animated-computing-machine/set.yml
    params:
      out1: 1
      out2: 1
      out3: 1
      out4: 1
  - aggregate:
    - put: in1
      resource: in1y
      params:
        file: out1/bit
    - put: in2
      resource: in2y
      params:
        file: out2/bit
    - put: in3
      resource: in3y
      params:
        file: out3/bit
    - put: in4
      resource: in4y
      params:
        file: out4/bit

#add bit 1

- name: xor1
  plan:
  - aggregate:
    - get: in1
      trigger: true
      resource: in1x
      passed: [setx]
    - get: in2
      trigger: true
      resource: in1y
      passed: [sety]
    - get: animated-computing-machine
  - task: xor
    file: animated-computing-machine/gates/xor.yml
  - put: out
    resource: out1
    params:
      file: out/bit

- name: and1
  plan:
  - aggregate:
    - get: in1
      trigger: true
      resource: in1x
      passed: [setx]
    - get: in2
      trigger: true
      resource: in1y
      passed: [sety]
    - get: animated-computing-machine
  - task: and
    file: animated-computing-machine/gates/and.yml
  - put: out
    resource: c1
    params:
      file: out/bit

#add bit 2

- name: xor2a
  plan:
  - aggregate:
    - get: in1
      trigger: true
      resource: in2x
      passed: [setx]
    - get: in2
      trigger: true
      resource: in2y
      passed: [sety]
    - get: animated-computing-machine
  - task: xor
    file: animated-computing-machine/gates/xor.yml
  - put: out
    resource: out2
    params:
      file: out/bit

- name: xor2b
  plan:
  - aggregate:
    - get: in1
      trigger: true
      resource: out2
      passed: [xor2a]
    - get: in2
      trigger: true
      resource: c1
      passed: [and1]
    - get: animated-computing-machine
  - task: xor
    file: animated-computing-machine/gates/xor.yml
  - put: out
    resource: out2
    params:
      file: out/bit

- name: and2a
  plan:
  - aggregate:
    - get: in1
      trigger: true
      resource: in2x
      passed: [setx]
    - get: in2
      trigger: true
      resource: in2y
      passed: [sety]
    - get: animated-computing-machine
  - task: and
    file: animated-computing-machine/gates/and.yml
  - put: out
    resource: c2
    params:
      file: out/bit

- name: and2b
  plan:
  - aggregate:
    - get: in1
      trigger: true
      resource: out2
      passed: [xor2a]
    - get: in2
      trigger: true
      resource: c1
      passed: [and1]
    - get: animated-computing-machine
  - task: and
    file: animated-computing-machine/gates/and.yml
  - put: out
    resource: c2
    params:
      file: out/bit

- name: or2
  plan:
  - aggregate:
    - get: in1
      trigger: true
      resource: c2
      passed: [and2a]
    - get: in2
      trigger: true
      resource: c2
      passed: [and2b]
    - get: animated-computing-machine
  - task: xor
    file: animated-computing-machine/gates/xor.yml
  - put: out
    resource: c2
    params:
      file: out/bit

#add bit 3

- name: xor3a
  plan:
  - aggregate:
    - get: in1
      trigger: true
      resource: in3x
      passed: [setx]
    - get: in2
      trigger: true
      resource: in3y
      passed: [sety]
    - get: animated-computing-machine
  - task: xor
    file: animated-computing-machine/gates/xor.yml
  - put: out
    resource: out3
    params:
      file: out/bit

- name: xor3b
  plan:
  - aggregate:
    - get: in1
      trigger: true
      resource: out3
      passed: [xor3a]
    - get: in2
      trigger: true
      resource: c2
      passed: [or2]
    - get: animated-computing-machine
  - task: xor
    file: animated-computing-machine/gates/xor.yml
  - put: out
    resource: out3
    params:
      file: out/bit

- name: and3a
  plan:
  - aggregate:
    - get: in1
      trigger: true
      resource: in3x
      passed: [setx]
    - get: in2
      trigger: true
      resource: in3y
      passed: [sety]
    - get: animated-computing-machine
  - task: and
    file: animated-computing-machine/gates/and.yml
  - put: out
    resource: c3
    params:
      file: out/bit

- name: and3b
  plan:
  - aggregate:
    - get: in1
      trigger: true
      resource: out3
      passed: [xor3a]
    - get: in2
      trigger: true
      resource: c2
      passed: [or2]
    - get: animated-computing-machine
  - task: and
    file: animated-computing-machine/gates/and.yml
  - put: out
    resource: c3
    params:
      file: out/bit

- name: or3
  plan:
  - aggregate:
    - get: in1
      trigger: true
      resource: c3
      passed: [and3a]
    - get: in2
      trigger: true
      resource: c3
      passed: [and3b]
    - get: animated-computing-machine
  - task: xor
    file: animated-computing-machine/gates/xor.yml
  - put: out
    resource: c3
    params:
      file: out/bit

#add bit 3

- name: xor4a
  plan:
  - aggregate:
    - get: in1
      trigger: true
      resource: in4x
      passed: [setx]
    - get: in2
      trigger: true
      resource: in4y
      passed: [sety]
    - get: animated-computing-machine
  - task: xor
    file: animated-computing-machine/gates/xor.yml
  - put: out
    resource: out4
    params:
      file: out/bit

- name: xor4b
  plan:
  - aggregate:
    - get: in1
      trigger: true
      resource: out4
      passed: [xor4a]
    - get: in2
      trigger: true
      resource: c3
      passed: [or3]
    - get: animated-computing-machine
  - task: xor
    file: animated-computing-machine/gates/xor.yml
  - put: out
    resource: out4
    params:
      file: out/bit

- name: and4a
  plan:
  - aggregate:
    - get: in1
      trigger: true
      resource: in4x
      passed: [setx]
    - get: in2
      trigger: true
      resource: in4y
      passed: [sety]
    - get: animated-computing-machine
  - task: and
    file: animated-computing-machine/gates/and.yml
  - put: out
    resource: c4
    params:
      file: out/bit

- name: and4b
  plan:
  - aggregate:
    - get: in1
      trigger: true
      resource: out4
      passed: [xor4a]
    - get: in2
      trigger: true
      resource: c3
      passed: [or3]
    - get: animated-computing-machine
  - task: and
    file: animated-computing-machine/gates/and.yml
  - put: out
    resource: c4
    params:
      file: out/bit

- name: or4
  plan:
  - aggregate:
    - get: in1
      trigger: true
      resource: c4
      passed: [and4a]
    - get: in2
      trigger: true
      resource: c4
      passed: [and4b]
    - get: animated-computing-machine
  - task: xor
    file: animated-computing-machine/gates/xor.yml
  - put: out
    resource: c4
    params:
      file: out/bit

# final print

- name: print
  plan:
  - aggregate:
    - get: in1
      resource: c4
      trigger: true
      passed: [or4]
    - get: in2
      resource: out4
      trigger: true
      passed: [xor4b]
    - get: in3
      resource: out3
      trigger: true
      passed: [xor3b]
    - get: in4
      resource: out2
      trigger: true
      passed: [xor2b]
    - get: in5
      resource: out1
      trigger: true
      passed: [xor1]
  - task: print
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: alpine
      inputs:
      - name: in1
      - name: in2
      - name: in3
      - name: in4
      - name: in5
      run:
        path: sh
        args:
        - -exc
        - |
          echo "$(cat in1/bit)$(cat in2/bit)$(cat in3/bit)$(cat in4/bit)$(cat in5/bit)"

