---
resources:
- name: animated-computing-machine
  type: git
  source:
    uri: https://github.com/zaksoup/animated-computing-machine.git
    branch: master

- name: in1
  type: s3
  source:
    bucket: animated-computing-machine
    versioned_file: in1/bit
    access_key_id: {{access-key-id}}
    secret_access_key: {{secret-access-key}}
    region_name: us-west-2

- name: in2
  type: s3
  source:
    bucket: animated-computing-machine
    versioned_file: in2/bit
    access_key_id: {{access-key-id}}
    secret_access_key: {{secret-access-key}}
    region_name: us-west-2

jobs:
- name: set
  plan:
  - get: animated-computing-machine
  - task: set
    file: set.yml
    params:
      out1: 1
      out2: 0
  - aggregate:
    - put: in1
      resource: in1
      params:
        file: out1/bit
    - put: in2
      resource: in2
      params:
        file: out2/bit

- name: and
  plan:
  - aggregate:
    - get: in1
      resource: in1
      passed: [set]
    - get: in2
      resource: in1
      passed: [set]
    - get: animated-computing-machine
  - task: and
    file: animated-computing-machine/gates/and.yml

