---
resources:
- name: animated-computing-machine
  type: git
  source:
    uri: https://github.com/zaksoup/animated-computing-machine.git
    branch: master

- name: in1
  type: s3
  source:
    bucket: animated-computing-machine
    versioned_file: in1/bit
    access_key_id: {{access-key-id}}
    secret_access_key: {{secret-access-key}}
    region_name: us-west-2

- name: in2
  type: s3
  source:
    bucket: animated-computing-machine
    versioned_file: in2/bit
    access_key_id: {{access-key-id}}
    secret_access_key: {{secret-access-key}}
    region_name: us-west-2

- name: out1
  type: s3
  source:
    bucket: animated-computing-machine
    versioned_file: out1/bit
    access_key_id: {{access-key-id}}
    secret_access_key: {{secret-access-key}}
    region_name: us-west-2

- name: c1
  type: s3
  source:
    bucket: animated-computing-machine
    versioned_file: c1/bit
    access_key_id: {{access-key-id}}
    secret_access_key: {{secret-access-key}}
    region_name: us-west-2

jobs:
- name: set
  plan:
  - get: animated-computing-machine
  - task: set
    file: animated-computing-machine/set.yml
    params:
      out1: 1
      out2: 1
  - aggregate:
    - put: in1
      resource: in1
      params:
        file: out1/bit
    - put: in2
      resource: in2
      params:
        file: out2/bit

- name: xor
  plan:
  - aggregate:
    - get: in1
      trigger: true
      resource: in1
      passed: [set]
    - get: in2
      trigger: true
      resource: in2
      passed: [set]
    - get: animated-computing-machine
  - task: xor
    file: animated-computing-machine/gates/xor.yml
  - put: out
    resource: out1
    params:
      file: out/bit

- name: and
  plan:
  - aggregate:
    - get: in1
      trigger: true
      resource: in1
      passed: [set]
    - get: in2
      trigger: true
      resource: in2
      passed: [set]
    - get: animated-computing-machine
  - task: and
    file: animated-computing-machine/gates/and.yml
  - put: out
    resource: c1
    params:
      file: out/bit

- name: print
  plan:
  - aggregate:
    - get: in1
      resource: out1
      trigger: true
      passed: [xor]
    - get: in2
      resource: c1
      trigger: true
      passed: [and]
  - task: print
    config:
      run:
        path: sh
        args:
        - -exc
        - |
          cat -n in1/bit
          cat -n in2/bit

